### ISSUE TITLE
Cannot auth via HTTP only (HTTPS works)

### ISSUE THREAD

**Issue by JersyJ** [samuong/alpaca#134]
Hi, 

I am not able to authenticate to proxy via HTTP only request (e.g. http://google.com). Request with HTTPS (e.g. https://google.com) works without the problem.

curl with http url works.
`curl --proxy <proxy> --proxy-ntlm --proxy-user "<username>" -v http://google.com`

The logs:
```
2024/07/31 10:16:38.021190 proxyfinder.go:135: [1] GET http://google.com/ via "PROXY <PROXY_EXAMPLE>"
2024/07/31 10:16:38.202948 proxy.go:208: [1] Got "407 Proxy Authentication Required" response, retrying with auth
```
After that I will get 407 response.

Otherwise, the app works great :D

**Comment by samuong** [comment]
Hi @JersyJ, thanks for the bug report.

When you use curl, what NTLM domain are you using? Does your `<username>` look like `<domain>\\<user>` or `<user>@<domain>` or are you just passing a user name?

And when you start alpaca, how are you passing your NTLM credentials? Are you using the `-domain` flag?

**Comment by JersyJ** [comment]
My <username> looks like <domain>\\<user> . Specifically, I am passing it with only one backslash and quotes ("<domain>\<user>") but both works even with 2 backslashes ("<domain>\\<user>").

I was always using the domain and then user separately like that:
`alpaca -d "<domain>" -u "<user>" -C "<pac_url>"`

I am also facing an issue when using non-interactive launch with credentials provided by the `-H` parameter, which looks correct to me, as shown in your example.

I have also been debugging and found differences in the Proxy-Authorization headers (NTLM TlRMTV...) generated by `Alpaca` and `curl`. The header from `Alpaca` is missing the hostname, which I believe is acceptable. However, I noticed that there were whitespaces between every character of the domain and name. I'm not sure if this is relevant as this isn't exactly my field of expertise, but I wanted to mention it.

**Comment by samuong** [comment]
@JersyJ sorry for the delay, I had this typed up in a tab but I just realised I never actually hit the "Comment" button...

It looks like you're invoking alpaca correctly. I'm not sure what's going wrong with your use of the `-H` flag but for now I'm guessing it's a related issue, maybe we can come back to it once we've figured out what's going wrong with your http request.

Having whitespace between every character of the domain and username sounds strange. Which whitespace character is it? Specifically, is it a space or tab or newline, or is it a nul character (i.e., `\x00`)? If it's the latter, then it might be expected, it's the UTF16 representation which is used by NTLM (or at least by the https://github.com/azure/go-ntlmssp package that alpaca depends on).

Does this whitespace behaviour only happen when you're visiting an http:// url, or does it also happen with say https://google.com?

**Comment by JersyJ** [comment]
Hi @samuong,
Thanks for your patience! I was previously using Alpaca with YouTube running in the background to stay authenticated while developing 😄.  The problem is not in -H flag, also not with the whitespace character probably. I’ve now had time to revisit the debugging process with a better understanding, and here’s what I’ve found:

I compared the Alpaca requests and equivalent curl requests using Wireshark, and identified the following differences:

## Type 1

### Curl: 
- Negotiate flags: 0x00088206
- Calling workstation: NULL
- Calling workstation name: NULL

### Alpaca:
- Negotiate flags: 0xa0883001
- Calling workstation: <domain>
- Calling workstation name: <hostname>

## Type 2

### Curl: 
- Target Name: <NetBIOS domain name>
- Negotiate flags: 0x00898206


### Alpaca:
- Target Name: NULL
- Negotiate flags: 0xa0880201

## Type 3

### Curl: 
- (deprecated in NTLMv2) - Lan Manager Response: <hash string>
- NTLM Response: Offset 88
- Host name:  <hostname>
- Negotiate Flags: 0x00898206

### Alpaca:
(deprecated in NTLMv2) - Lan Manager Response: EMPTY
- NTLM Response: Offset 64
- Host name: NULL
- Negotiate Flags: 0xa0880201

and another header with:
Accept-Encoding: gzip \r\n

Do you have any insights into what might be going wrong?

**Comment by JersyJ** [comment]
I've attempted various configurations of the Negotiate Flags, excluding the Unicode flag, and numerous other combinations, but the authentication continues to fail. In the Type 1 message, I set the Negotiate Target Info flag to prompt the inclusion of the Target Name in the Type 2 message. The Target Name successfully showed up. 

Additionally, I hardcoded the hostname into the Type 3 message, however, this approach didn't resolve the issue either. I'm uncertain whether the hostname plays a role in hash generation or another critical part of the NTLM authentication sequence.

This leads me to suspect that the issue might be related to Unicode handling or specific configurations set by our IT department for the proxy.

**Comment by samuong** [comment]
Hi @JersyJ, thanks for looking into this so thoroughly, especially the negotiate flags on all the ntlm messages. One thing that jumps out at me is:

In curl's type 1 message, you've got `Calling workstation: < domain >`, is this domain different from the one in the type 2 message that alpaca receives in `Target Name: < NetBIOS domain name >`? The library that we use to do auth doesn't really handle this case well when these two domains are different, and it's possible there are still bugs or missing functionality that you're running into.

The Azure/go-ntlmssp library was written by a team in Microsoft Azure for their specific needs, and doesn't implement the whole protocol (most noticeably it only does NTLMv2, not older versions). It's less complete than the curl implementation, and as a result the initial (and therefore subsequent) negotiate flags and code paths will be different.

It might be easier to move to a new library, such as https://github.com/bodgit/ntlmssp (or maybe even a cgo binding for libcurl?), which would require some small changes to [authenticator.go](../blob/master/authenticator.go) to use that library instead. It might be a few months before I'll be able to find time to make a change like that, but in the meantime I just wanted to check if that's something you might be interested in having a go at? In any case, I'd need your help to test the changes to make sure they fix your bug.

**Comment by samuong** [comment]
I think the change would look something like #143, the only tricky part is that the library expects a plaintext password instead of a hash. So moving to github.com/bodgit/ntlmssp would require some changes to how alpaca manages credentials (e.g. the `NTLM_CREDENTIALS` env var) and how users use it.

But it would be useful to know if this fixes your issue. Are you able to give this a try, with the environment variable `ALPACA_PASSWORD` set to your password? If you're not able to build it yourself, you can download a binary from one of the GitHub runners:

- mac/amd64: https://github.com/samuong/alpaca/actions/runs/14416427133/artifacts/2931929440
- mac/arm64: https://github.com/samuong/alpaca/actions/runs/14416427133/artifacts/2931930284
- linux/amd64: https://github.com/samuong/alpaca/actions/runs/14416427133/artifacts/2931929099
- linux/arm64: https://github.com/samuong/alpaca/actions/runs/14416427133/artifacts/2931929212

Sorry I think the Windows action is broken, it doesn't seem to find an artifact to upload...

**Comment by JersyJ** [comment]
> In curl's type 1 message, you've got `Calling workstation: < domain >`, is this domain different from the one in the type 2 message that alpaca receives in `Target Name: < NetBIOS domain name >`? The library that we use to do auth doesn't really handle this case well when these two domains are different, and it's possible there are still bugs or missing functionality that you're running into.

Yes, the domain is completely different. If I understand it correctly, authentication is happening across domains, so the machine sending the Type 1 message belongs to a different domain than the one targeted in the Type 2 message.

> The Azure/go-ntlmssp library was written by a team in Microsoft Azure for their specific needs, and doesn't implement the whole protocol (most noticeably it only does NTLMv2, not older versions). It's less complete than the curl implementation, and as a result the initial (and therefore subsequent) negotiate flags and code paths will be different.

Understood. 

> But it would be useful to know if this fixes your issue. Are you able to give this a try, with the environment variable `ALPACA_PASSWORD` set to your password? If you're not able to build it yourself, you can download a binary from one of the GitHub runners:

As for testing: I’ve built it myself, set the `ALPACA_PASSWORD` environment variable, and also tried modifying the negotiate flags but it still fails like with the former (Azure) library :( . The handshake in this library looks almost fully implemented, possibly even more complete than curl.

Btw I think the hash-based approach is much better overall in terms of security.

**Comment by samuong** [comment]
Ok, if that library also fails, then I'll hold off on swapping the Azure library to that one. Thanks for testing it.

At this point, I can't really think of any issue that could be causing this other than a missing feature in the libraries that we're using. Unless there is a way to reproduce this auth failure using an environment I can access (e.g. Samba and Squid?) then I think debugging the library is not going to be possible.

I took a first stab at using another library (https://github.com/omniboost/ThomsonReutersEikon-go-ntlm) but haven't found time to do much testing yet. If you manage to find time to test it before I do, please let me know how it goes?

Also I agree that the hash-based approach is better and I would make sure to do this if we settle on an approach to fix this bug. But for now the `ALPACA_PASSWORD` env var is a bit quicker to implement and test.

**Comment by gaitovrat** [comment]
Hi @samuong, I had the same issue and tested your branch with both `http://google.com` and `https://google.com` - both worked. Hope your PR gets merged soon!

**Comment by gaitovrat** [comment]
Hi @samuong, I did wrong testing. @JersyJ corrected me and your pull request is not working. It is also returning `407 Proxy Authentication Required`. And besides that I have exception stacktrace:
```
goroutine 35 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1947 +0xbe
panic({0x980660?, 0xe91ba0?})
        /usr/local/go/src/runtime/panic.go:792 +0x132
github.com/ThomsonReutersEikon/go-ntlm/ntlm.(*V2ClientSession).ProcessChallengeMessage(0xc0001fe000, 0xc0001fc000)
        /home/ratmir/go/pkg/mod/github.com/omniboost/!thomson!reuters!eikon-go-ntlm@v0.0.0-20200629081634-2b904c46aa41/ntlm/ntlmv2.go:338>
main.authenticator.do({{0xc000026019, 0x5}, {0xc000026011, 0x7}, {0xc000012760, 0x10, 0x10}}, 0xc0000ec280, {0xae8040, 0xc0003c01a0})
        /home/ratmir/alpaca/authenticator.go:74 +0x654
main.ProxyHandler.proxyRequest({0xc0003c01a0?, 0xc00003d800?, 0xc0003abbb0?}, {0xaecab8, 0xc000564000}, 0xc0000ec280, 0xc00003d800)
        /home/ratmir/alpaca/proxy.go:215 +0xd15
main.ProxyHandler.ServeHTTP({0xc0003c01a0?, 0xc00003d800?, 0xc0003abbb0?}, {0xaecab8, 0xc000564000}, 0xc0000ec280)
        /home/ratmir/alpaca/proxy.go:67 +0xbc
main.createServer.ProxyHandler.WrapHandler.func2({0xaecab8?, 0xc000564000?}, 0xae3fe0?)
        /home/ratmir/alpaca/proxy.go:51 +0x6d
net/http.HandlerFunc.ServeHTTP(0xc000562140?, {0xaecab8?, 0xc000564000?}, 0xae3fe0?)
        /usr/local/go/src/net/http/server.go:2294 +0x29
main.createServer.(*ProxyFinder).WrapHandler.func3({0xaecab8, 0xc000564000}, 0xc000562140)
        /home/ratmir/alpaca/proxyfinder.go:67 +0xe2
net/http.HandlerFunc.ServeHTTP(0xc000562000?, {0xaecab8?, 0xc000564000?}, 0xae3fa0?)
        /usr/local/go/src/net/http/server.go:2294 +0x29
main.createServer.AddContextID.func4({0xaecab8, 0xc000564000}, 0xc000562000)
        /home/ratmir/alpaca/contextid.go:36 +0xbd
net/http.HandlerFunc.ServeHTTP(0x472559?, {0xaecab8?, 0xc000564000?}, 0xc000439b70?)
        /usr/local/go/src/net/http/server.go:2294 +0x29
net/http.serverHandler.ServeHTTP({0xc0003bc660?}, {0xaecab8?, 0xc000564000?}, 0x1?)
        /usr/local/go/src/net/http/server.go:3301 +0x8e
net/http.(*conn).serve(0xc0001122d0, {0xaed950, 0xc0003bc570})
        /usr/local/go/src/net/http/server.go:2102 +0x625
created by net/http.(*Server).Serve in goroutine 34
        /usr/local/go/src/net/http/server.go:3454 +0x485
```
